# Generated by Django 3.0.9 on 2022-05-08 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.Role'),
        ),
    ]
