# Generated by Django 3.0.9 on 2022-05-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugType',
            fields=[
                ('bug_type_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bug_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('bug_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bug_desc', models.CharField(max_length=280)),
                ('bug_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.BugType')),
            ],
        ),
    ]
