# Generated by Django 3.0.9 on 2022-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20220508_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugPriority',
            fields=[
                ('bug_priority_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bug_priority', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='bugtype',
            name='bug_type',
            field=models.CharField(max_length=100),
        ),
    ]
