# Generated by Django 3.0.9 on 2022-05-08 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0004_bug_bug_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugStatus',
            fields=[
                ('bug_status_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bug_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='bug_owner',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
