# Generated by Django 3.0.9 on 2022-05-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20220508_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugstatus',
            name='bug_status',
            field=models.CharField(max_length=20),
        ),
    ]
