# Generated by Django 3.0.9 on 2022-05-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_bughistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
